;; -*- mode: eask; lexical-binding: t -*-

(package "up-doc"
         "0.0.1"
         "Doctor for your use-package")

(website-url "https://github.com/joshbax189/up-doc-el")
(keywords "lisp")

(package-file "up-doc.el")

(script "test" "eask test ert test/up-doc.test.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "dash" "2.20.0")
(development
 (depends-on "el-mock" "1.25.1"))
